# Generated by Django 4.2.13 on 2024-05-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("numeric_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("numeric_id", models.AutoField(primary_key=True, serialize=False)),
                ("theme", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("numeric_id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("size", models.IntegerField()),
                ("type", models.CharField(max_length=10)),
                ("creation_time", models.DateTimeField()),
                ("modification_time", models.DateTimeField()),
                (
                    "persons",
                    models.ManyToManyField(related_name="files", to="catalogo.person"),
                ),
                (
                    "themes",
                    models.ManyToManyField(related_name="files", to="catalogo.theme"),
                ),
            ],
        ),
    ]
